(function () {
  const STORAGE_KEY = 'aligor-language';

  const translations = {
    en: {
      'nav.home': 'Home',
      'nav.articles': 'Articles',
      'nav.typeless': 'Typeless',
      'nav.about': 'About',
      'nav.downloads': 'Downloads',
      'nav.notes': 'Notes',
      'nav.hotmail': 'Hotmail Guide',
      'home.eyebrow': 'Personal sharing blog',
      'home.title': 'I am 阿理哥 (Aligor). I share <span class="gradient">AI and tech knowledge</span>.',
      'home.intro': 'I am currently focused on sharing AI tools, technology knowledge, and practical ideas that help people understand and use tech with more confidence.',
      'home.cta.read': 'Read latest notes',
      'home.cta.follow': 'Follow me',
      'home.cta.typeless': 'Typeless for you',
      'home.profile.title': 'I am 阿理哥 (Aligor).',
      'home.profile.body': 'I created aligor as my personal sharing space. I regularly analyze useful AI tools, tech trends, and simple ways to improve technology awareness.',
      'home.follow.label': 'Follow aligor',
      'home.follow.title': 'Follow my AI and tech updates',
      'home.follow.body': 'I will keep sharing content that helps you understand AI, choose better tools, and build stronger technology awareness.',
      'home.latest.title': 'Latest articles',
      'home.latest.label': 'Journal notes',
      'home.loading.label': 'Loading',
      'home.loading.body': 'Loading articles...',
      'home.about.title': 'About aligor',
      'home.about.label': 'Profile and links',
      'home.about.cardTitle': 'What I share',
      'home.about.cardBody': '<strong>aligor</strong> is where I share AI and technology knowledge in a practical, personal way. I focus on useful tools, tech awareness, and simple explanations that help people learn faster.',
      'home.tool.typeless': 'Typeless for You',
      'home.tool.typelessMeta': 'Download guide',
      'home.tool.articles': 'Latest articles',
      'home.tool.articlesMeta': 'Read notes',
      'home.tool.hotmail': 'Link AI Agent with Hotmail',
      'home.tool.hotmailMeta': 'OAuth2 guide',
      'card.read': 'Read',
      'empty.noPosts': 'No posts',
      'empty.noPostsBody': 'No articles yet. Drop a markdown file into <code>/articles/</code> and add it to <code>articles.json</code>.',
      'empty.error': 'Error',
      'empty.errorBody': 'Could not load articles. Check that <code>articles.json</code> is valid.',
      'article.back': 'Back to all articles',
      'article.loading': 'Loading article...',
      'footer.made': 'Made with',
      'typeless.eyebrow': 'Typeless for you',
      'typeless.title': 'Pick your <span class="gradient">download</span>',
      'typeless.intro': 'Smart voice dictation that turns speech into clear, polished writing on desktop and mobile.',
      'typeless.desktop.title': 'Desktop',
      'typeless.desktop.desc': 'Use Typeless on your computer for writing, replies, documents, and daily work.',
      'typeless.download.macos': 'Download for macOS',
      'typeless.download.windows': 'Download for Windows',
      'typeless.mobile.title': 'Mobile',
      'typeless.mobile.desc': 'Scan the QR code or use the store buttons to install Typeless on your phone.',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': 'Important tip',
      'typeless.tip.title': 'Use different emails on phone and computer',
      'typeless.tip.body': 'Typeless has a free weekly allowance. You can use up to <strong>8,000 words per week</strong>, and the allowance resets every Monday. If you install Typeless on both mobile and computer and want separate weekly word limits, do not use the same email on both devices.',
      'typeless.follow.label': 'Follow aligor',
      'typeless.follow.title': 'Follow me for more tech learning content',
      'typeless.follow.body': 'I regularly share analysis and practical content to help everyone improve their technology awareness and understand useful AI tools.',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': 'AI agent email setup',
      'hotmail.title': 'How to link an AI agent with a <span class="gradient">personal Hotmail account</span>',
      'hotmail.intro': 'Use Microsoft OAuth2 so the account owner signs in safely, gives consent, and your AI agent can connect to Hotmail through IMAP without collecting the email password.',
      'hotmail.badge.safe': 'OAuth2 only',
      'hotmail.badge.personal': 'Personal Hotmail / Outlook.com',
      'hotmail.badge.imap': 'IMAP access',
      'hotmail.overview.title': 'Standard Structure',
      'hotmail.overview.body': 'This guide is for a personal Microsoft account such as Hotmail, Outlook.com, or Live.com. The clean setup is: register an app, request delegated mail scopes, sign the user in with Microsoft, exchange the authorization code for tokens, then connect to IMAP with XOAUTH2.',
      'hotmail.steps.title': 'Setup Steps',
      'hotmail.step1.title': 'Register your Microsoft app',
      'hotmail.step1.body': 'Create an app in Microsoft Entra. Choose personal Microsoft accounts, or both work and personal accounts if your agent supports both. Add your real redirect URL, such as your agent callback page.',
      'hotmail.step2.title': 'Add delegated permissions',
      'hotmail.step2.body': 'Request only what you need. For IMAP reading, use offline_access and IMAP.AccessAsUser.All. Add SMTP.Send only if your agent must send email.',
      'hotmail.step3.title': 'Send the user to Microsoft login',
      'hotmail.step3.body': 'Open the Microsoft authorization URL with your client_id, redirect_uri, response_type=code, scopes, and state. For public clients, use PKCE.',
      'hotmail.step4.title': 'Exchange the code for tokens',
      'hotmail.step4.body': 'Your backend exchanges the authorization code at the token endpoint. Store refresh tokens securely and use them to get fresh access tokens when needed.',
      'hotmail.step5.title': 'Connect to Outlook IMAP',
      'hotmail.step5.body': 'Connect to outlook.office365.com on port 993 with SSL/TLS. Authenticate with XOAUTH2 using the user email and the access token.',
      'hotmail.step6.title': 'Refresh and protect access',
      'hotmail.step6.body': 'Access tokens expire. Refresh them quietly, encrypt stored tokens, and give the user a way to disconnect the agent.',
      'hotmail.config.title': 'Important Values',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': 'Main scopes',
      'hotmail.config.xoauth': 'XOAUTH2 format',
      'hotmail.safety.title': 'Safety Rules',
      'hotmail.safety.one': 'Never ask users to type their Hotmail password into your AI agent.',
      'hotmail.safety.two': 'Use the least permissions needed for the agent task.',
      'hotmail.safety.three': 'Encrypt refresh tokens and do not expose them to the browser.',
      'hotmail.safety.four': 'Let users revoke or disconnect access anytime.',
      'hotmail.trouble.title': 'Quick Troubleshooting',
      'hotmail.trouble.auth': 'AUTHENTICATE failed usually means the token is expired, the scope is wrong, or the client is not using XOAUTH2.',
      'hotmail.trouble.grant': 'invalid_grant usually means the code expired, PKCE failed, or the redirect URI does not match.',
      'hotmail.trouble.consumer': 'For personal Hotmail accounts, use the consumers Microsoft login tenant.',
      'hotmail.references.title': 'Official References',
      'hotmail.references.body': 'This page is based on Microsoft Learn documentation for OAuth, IMAP/SMTP authentication, and Microsoft identity app registration.'
    },
    zh: {
      'nav.home': '首页',
      'nav.articles': '文章',
      'nav.typeless': 'Typeless',
      'nav.about': '关于',
      'nav.downloads': '下载',
      'nav.notes': '提示',
      'nav.hotmail': 'Hotmail 教程',
      'home.eyebrow': '个人分享博客',
      'home.title': '我是阿理哥。我分享 <span class="gradient">AI 与科技知识</span>。',
      'home.intro': '我目前主要分享 AI 工具、科技知识和实用想法，帮助大家更有信心地理解和使用科技。',
      'home.cta.read': '阅读最新笔记',
      'home.cta.follow': '追踪我',
      'home.cta.typeless': 'Typeless 下载',
      'home.profile.title': '我是阿理哥。',
      'home.profile.body': '我把 aligor 做成我的个人分享空间。我会定期分析实用 AI 工具、科技趋势，以及帮助大家提升科技认知的简单方法。',
      'home.follow.label': 'Follow aligor',
      'home.follow.title': '追踪我的 AI 与科技更新',
      'home.follow.body': '我会持续分享帮助你理解 AI、选择更好工具、提升科技认知的内容。',
      'home.latest.title': '最新文章',
      'home.latest.label': '个人笔记',
      'home.loading.label': '载入中',
      'home.loading.body': '正在载入文章...',
      'home.about.title': '关于 aligor',
      'home.about.label': '个人介绍与链接',
      'home.about.cardTitle': '我分享什么',
      'home.about.cardBody': '<strong>aligor</strong> 是我用个人化、实用方式分享 AI 与科技知识的地方。我会专注在实用工具、科技认知和简单易懂的解释，帮助大家更快学习。',
      'home.tool.typeless': 'Typeless 下载页',
      'home.tool.typelessMeta': '下载指南',
      'home.tool.articles': '最新文章',
      'home.tool.articlesMeta': '阅读笔记',
      'home.tool.hotmail': 'AI Agent 连接 Hotmail',
      'home.tool.hotmailMeta': 'OAuth2 教程',
      'card.read': '阅读',
      'empty.noPosts': '暂无文章',
      'empty.noPostsBody': '还没有文章。把 markdown 文件放进 <code>/articles/</code>，再加入 <code>articles.json</code>。',
      'empty.error': '错误',
      'empty.errorBody': '文章载入失败。请检查 <code>articles.json</code> 是否正确。',
      'article.back': '回到全部文章',
      'article.loading': '正在载入文章...',
      'footer.made': '制作',
      'typeless.eyebrow': 'Typeless 下载',
      'typeless.title': '选择你的 <span class="gradient">下载版本</span>',
      'typeless.intro': 'Typeless 是智能语音输入工具，可以把你说的话变成更清楚、更顺的文字，手机和电脑都可以使用。',
      'typeless.desktop.title': '电脑版本',
      'typeless.desktop.desc': '在电脑上使用 Typeless，适合写文章、回复信息、整理文件和日常工作。',
      'typeless.download.macos': '下载 macOS 版本',
      'typeless.download.windows': '下载 Windows 版本',
      'typeless.mobile.title': '手机版本',
      'typeless.mobile.desc': '扫描 QR code，或点击 App Store / Google Play 按钮安装 Typeless。',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': '重要小贴士',
      'typeless.tip.title': '手机和电脑请使用不同邮箱',
      'typeless.tip.body': 'Typeless 有免费的每周字数额度。你每个星期可以免费使用 <strong>8,000 字</strong>，额度会在每个星期一重置。如果你同时在手机和电脑安装 Typeless，想要分开计算每周字数额度，就不要在两个设备使用同一个邮箱。手机用一个邮箱，电脑用另一个邮箱。',
      'typeless.follow.label': 'Follow aligor',
      'typeless.follow.title': '追踪我，学习更多科技认知内容',
      'typeless.follow.body': '我会定期分析和分享帮助大家提升科技认知的内容，也会介绍实用 AI 工具和使用方法。',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': 'AI Agent 邮箱连接',
      'hotmail.title': '如何把 AI Agent 连接到 <span class="gradient">个人 Hotmail 账号</span>',
      'hotmail.intro': '建议使用 Microsoft OAuth2，让账号本人安全登录并授权。这样 AI Agent 可以通过 IMAP 连接 Hotmail，不需要收集用户的邮箱密码。',
      'hotmail.badge.safe': '只用 OAuth2',
      'hotmail.badge.personal': '个人 Hotmail / Outlook.com',
      'hotmail.badge.imap': 'IMAP 读取',
      'hotmail.overview.title': '标准结构',
      'hotmail.overview.body': '这个教程适合个人 Microsoft 账号，例如 Hotmail、Outlook.com 或 Live.com。标准流程是：注册应用、申请 delegated mail scopes、让用户使用 Microsoft 登录、用 authorization code 换 token，然后用 XOAUTH2 连接 IMAP。',
      'hotmail.steps.title': '设置步骤',
      'hotmail.step1.title': '注册 Microsoft 应用',
      'hotmail.step1.body': '在 Microsoft Entra 建立应用。账号类型选择个人 Microsoft 账号；如果你的 Agent 同时支持公司账号和个人账号，可以选择两者都支持。加入你的真实 redirect URL，例如 Agent 的 callback 页面。',
      'hotmail.step2.title': '加入 delegated permissions',
      'hotmail.step2.body': '只申请真正需要的权限。读取 IMAP 可以使用 offline_access 和 IMAP.AccessAsUser.All。如果 Agent 需要发邮件，才加入 SMTP.Send。',
      'hotmail.step3.title': '把用户带去 Microsoft 登录',
      'hotmail.step3.body': '打开 Microsoft authorization URL，并带上 client_id、redirect_uri、response_type=code、scopes 和 state。Public client 建议使用 PKCE。',
      'hotmail.step4.title': '用 code 换 tokens',
      'hotmail.step4.body': '你的 backend 在 token endpoint 使用 authorization code 换取 tokens。Refresh token 要安全保存，并用来更新 access token。',
      'hotmail.step5.title': '连接 Outlook IMAP',
      'hotmail.step5.body': '连接 outlook.office365.com，port 993，使用 SSL/TLS。认证方式使用 XOAUTH2，内容包含用户邮箱和 access token。',
      'hotmail.step6.title': '更新并保护访问权限',
      'hotmail.step6.body': 'Access token 会过期。系统需要自动 refresh，并加密保存 token，同时让用户可以随时取消连接。',
      'hotmail.config.title': '重要参数',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': '主要 scopes',
      'hotmail.config.xoauth': 'XOAUTH2 格式',
      'hotmail.safety.title': '安全规则',
      'hotmail.safety.one': '不要要求用户把 Hotmail 密码输入到 AI Agent。',
      'hotmail.safety.two': '只使用 Agent 任务真正需要的最少权限。',
      'hotmail.safety.three': 'Refresh token 必须加密保存，不要暴露给浏览器。',
      'hotmail.safety.four': '让用户可以随时 revoke 或 disconnect access。',
      'hotmail.trouble.title': '常见问题',
      'hotmail.trouble.auth': 'AUTHENTICATE failed 通常代表 token 过期、scope 错误，或 client 没有使用 XOAUTH2。',
      'hotmail.trouble.grant': 'invalid_grant 通常代表 code 过期、PKCE 验证失败，或 redirect URI 不一致。',
      'hotmail.trouble.consumer': '个人 Hotmail 账号请使用 consumers Microsoft login tenant。',
      'hotmail.references.title': '官方参考',
      'hotmail.references.body': '这个页面根据 Microsoft Learn 的 OAuth、IMAP/SMTP authentication 和 Microsoft identity app registration 文件整理。'
    },
    ms: {
      'nav.home': 'Laman utama',
      'nav.articles': 'Artikel',
      'nav.typeless': 'Typeless',
      'nav.about': 'Tentang',
      'nav.downloads': 'Muat turun',
      'nav.notes': 'Nota',
      'nav.hotmail': 'Panduan Hotmail',
      'home.eyebrow': 'Blog perkongsian peribadi',
      'home.title': 'Saya 阿理哥 (Aligor). Saya berkongsi <span class="gradient">ilmu AI dan teknologi</span>.',
      'home.intro': 'Saya kini fokus berkongsi alat AI, pengetahuan teknologi, dan idea praktikal supaya lebih ramai orang yakin memahami dan menggunakan teknologi.',
      'home.cta.read': 'Baca nota terkini',
      'home.cta.follow': 'Ikuti saya',
      'home.cta.typeless': 'Typeless untuk anda',
      'home.profile.title': 'Saya 阿理哥 (Aligor).',
      'home.profile.body': 'Saya menjadikan aligor sebagai ruang perkongsian peribadi. Saya kerap menganalisis alat AI, trend teknologi, dan cara mudah untuk meningkatkan kesedaran teknologi.',
      'home.follow.label': 'Ikuti aligor',
      'home.follow.title': 'Ikuti kemas kini AI dan teknologi saya',
      'home.follow.body': 'Saya akan terus berkongsi kandungan yang membantu anda memahami AI, memilih alat yang lebih baik, dan membina kesedaran teknologi yang lebih kuat.',
      'home.latest.title': 'Artikel terkini',
      'home.latest.label': 'Nota jurnal',
      'home.loading.label': 'Memuat',
      'home.loading.body': 'Sedang memuat artikel...',
      'home.about.title': 'Tentang aligor',
      'home.about.label': 'Profil dan pautan',
      'home.about.cardTitle': 'Apa yang saya kongsi',
      'home.about.cardBody': '<strong>aligor</strong> ialah tempat saya berkongsi ilmu AI dan teknologi secara praktikal dan peribadi. Saya fokus pada alat berguna, kesedaran teknologi, dan penerangan mudah supaya orang belajar dengan lebih cepat.',
      'home.tool.typeless': 'Typeless untuk Anda',
      'home.tool.typelessMeta': 'Panduan muat turun',
      'home.tool.articles': 'Artikel terkini',
      'home.tool.articlesMeta': 'Baca nota',
      'home.tool.hotmail': 'Hubungkan AI Agent dengan Hotmail',
      'home.tool.hotmailMeta': 'Panduan OAuth2',
      'card.read': 'Baca',
      'empty.noPosts': 'Tiada artikel',
      'empty.noPostsBody': 'Belum ada artikel. Letakkan fail markdown dalam <code>/articles/</code> dan tambahkannya ke <code>articles.json</code>.',
      'empty.error': 'Ralat',
      'empty.errorBody': 'Artikel gagal dimuat. Semak bahawa <code>articles.json</code> adalah sah.',
      'article.back': 'Kembali ke semua artikel',
      'article.loading': 'Sedang memuat artikel...',
      'footer.made': 'Dibuat dengan',
      'typeless.eyebrow': 'Typeless untuk anda',
      'typeless.title': 'Pilih <span class="gradient">muat turun</span> anda',
      'typeless.intro': 'Dikte suara pintar yang menukar percakapan kepada tulisan yang jelas dan kemas di desktop dan telefon.',
      'typeless.desktop.title': 'Desktop',
      'typeless.desktop.desc': 'Gunakan Typeless di komputer untuk menulis, membalas mesej, dokumen, dan kerja harian.',
      'typeless.download.macos': 'Muat turun untuk macOS',
      'typeless.download.windows': 'Muat turun untuk Windows',
      'typeless.mobile.title': 'Mudah alih',
      'typeless.mobile.desc': 'Imbas kod QR atau gunakan butang kedai aplikasi untuk memasang Typeless di telefon.',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': 'Tip penting',
      'typeless.tip.title': 'Gunakan e-mel berbeza di telefon dan komputer',
      'typeless.tip.body': 'Typeless mempunyai kuota percuma mingguan. Anda boleh menggunakan sehingga <strong>8,000 perkataan seminggu</strong>, dan kuota akan reset setiap hari Isnin. Jika anda memasang Typeless pada telefon dan komputer serta mahukan had mingguan berasingan, jangan gunakan e-mel yang sama pada kedua-dua peranti.',
      'typeless.follow.label': 'Ikuti aligor',
      'typeless.follow.title': 'Ikuti saya untuk lebih banyak kandungan teknologi',
      'typeless.follow.body': 'Saya kerap berkongsi analisis dan kandungan praktikal untuk membantu semua orang meningkatkan kesedaran teknologi dan memahami alat AI yang berguna.',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': 'Tetapan e-mel AI agent',
      'hotmail.title': 'Cara hubungkan AI agent dengan <span class="gradient">akaun Hotmail peribadi</span>',
      'hotmail.intro': 'Gunakan Microsoft OAuth2 supaya pemilik akaun boleh log masuk dengan selamat, beri kebenaran, dan AI agent boleh menyambung ke Hotmail melalui IMAP tanpa meminta kata laluan e-mel.',
      'hotmail.badge.safe': 'OAuth2 sahaja',
      'hotmail.badge.personal': 'Hotmail / Outlook.com peribadi',
      'hotmail.badge.imap': 'Akses IMAP',
      'hotmail.overview.title': 'Struktur Standard',
      'hotmail.overview.body': 'Panduan ini untuk akaun Microsoft peribadi seperti Hotmail, Outlook.com, atau Live.com. Aliran yang kemas ialah: daftar app, minta delegated mail scopes, minta pengguna log masuk dengan Microsoft, tukar authorization code kepada token, kemudian sambung ke IMAP dengan XOAUTH2.',
      'hotmail.steps.title': 'Langkah Tetapan',
      'hotmail.step1.title': 'Daftar app Microsoft',
      'hotmail.step1.body': 'Buat app dalam Microsoft Entra. Pilih akaun Microsoft peribadi, atau akaun kerja dan peribadi jika agent anda menyokong kedua-duanya. Masukkan redirect URL sebenar, seperti halaman callback agent anda.',
      'hotmail.step2.title': 'Tambah delegated permissions',
      'hotmail.step2.body': 'Minta hanya akses yang diperlukan. Untuk membaca IMAP, gunakan offline_access dan IMAP.AccessAsUser.All. Tambah SMTP.Send hanya jika agent perlu menghantar e-mel.',
      'hotmail.step3.title': 'Bawa pengguna ke Microsoft login',
      'hotmail.step3.body': 'Buka Microsoft authorization URL dengan client_id, redirect_uri, response_type=code, scopes, dan state. Untuk public client, gunakan PKCE.',
      'hotmail.step4.title': 'Tukar code kepada token',
      'hotmail.step4.body': 'Backend anda menukar authorization code di token endpoint. Simpan refresh token dengan selamat dan gunakannya untuk mendapatkan access token baharu.',
      'hotmail.step5.title': 'Sambung ke Outlook IMAP',
      'hotmail.step5.body': 'Sambung ke outlook.office365.com pada port 993 dengan SSL/TLS. Authenticate menggunakan XOAUTH2 bersama e-mel pengguna dan access token.',
      'hotmail.step6.title': 'Refresh dan lindungi akses',
      'hotmail.step6.body': 'Access token akan tamat tempoh. Refresh secara senyap, encrypt token yang disimpan, dan beri pengguna cara untuk disconnect agent.',
      'hotmail.config.title': 'Nilai Penting',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': 'Scopes utama',
      'hotmail.config.xoauth': 'Format XOAUTH2',
      'hotmail.safety.title': 'Peraturan Keselamatan',
      'hotmail.safety.one': 'Jangan minta pengguna menaip kata laluan Hotmail ke dalam AI agent.',
      'hotmail.safety.two': 'Gunakan permission paling minimum untuk tugasan agent.',
      'hotmail.safety.three': 'Encrypt refresh token dan jangan dedahkan kepada browser.',
      'hotmail.safety.four': 'Benarkan pengguna revoke atau disconnect akses bila-bila masa.',
      'hotmail.trouble.title': 'Troubleshooting Ringkas',
      'hotmail.trouble.auth': 'AUTHENTICATE failed biasanya bermaksud token tamat tempoh, scope salah, atau client tidak menggunakan XOAUTH2.',
      'hotmail.trouble.grant': 'invalid_grant biasanya bermaksud code tamat tempoh, PKCE gagal, atau redirect URI tidak sama.',
      'hotmail.trouble.consumer': 'Untuk akaun Hotmail peribadi, gunakan consumers Microsoft login tenant.',
      'hotmail.references.title': 'Rujukan Rasmi',
      'hotmail.references.body': 'Halaman ini berdasarkan dokumentasi Microsoft Learn untuk OAuth, pengesahan IMAP/SMTP, dan pendaftaran app Microsoft identity.'
    }
  };

  function getLanguage() {
    const saved = localStorage.getItem(STORAGE_KEY);
    return ['en', 'zh', 'ms'].includes(saved) ? saved : 'en';
  }

  function translateElement(el, lang) {
    const dictionary = translations[lang] || translations.en;
    const textKey = el.getAttribute('data-i18n');
    const htmlKey = el.getAttribute('data-i18n-html');

    if (htmlKey && dictionary[htmlKey]) {
      el.innerHTML = dictionary[htmlKey];
    } else if (textKey && dictionary[textKey]) {
      el.textContent = dictionary[textKey];
    }
  }

  function applyLanguage(lang) {
    const nextLang = ['en', 'zh', 'ms'].includes(lang) ? lang : 'en';
    document.documentElement.lang = nextLang === 'zh' ? 'zh-Hans' : nextLang;
    document.querySelectorAll('[data-i18n], [data-i18n-html]').forEach((el) => translateElement(el, nextLang));
    document.querySelectorAll('[data-lang-option]').forEach((button) => {
      const active = button.getAttribute('data-lang-option') === nextLang;
      button.classList.toggle('active', active);
      button.setAttribute('aria-pressed', active ? 'true' : 'false');
    });
  }

  window.aligorGetLang = getLanguage;
  window.aligorApplyLanguage = function () {
    applyLanguage(getLanguage());
  };

  document.addEventListener('click', (event) => {
    const button = event.target.closest('[data-lang-option]');
    if (!button) return;
    const selected = button.getAttribute('data-lang-option');
    const lang = ['en', 'zh', 'ms'].includes(selected) ? selected : 'en';
    localStorage.setItem(STORAGE_KEY, lang);
    applyLanguage(lang);
    window.dispatchEvent(new CustomEvent('aligor:languagechange', { detail: { lang } }));
  });

  document.addEventListener('DOMContentLoaded', () => applyLanguage(getLanguage()));
})();
