(function () {
  const STORAGE_KEY = 'aligor-language';

  const translations = {
    en: {
      'nav.home': 'Home',
      'nav.articles': 'Articles',
      'nav.typeless': 'Typeless',
      'nav.about': 'About',
      'nav.downloads': 'Downloads',
      'nav.notes': 'Notes',
      'nav.hotmail': 'Hotmail Guide',
      'home.eyebrow': 'Personal sharing blog',
      'home.title': 'I am 阿理哥 (Aligor). I share <span class="gradient">AI and tech knowledge</span>.',
      'home.intro': 'I am currently focused on sharing AI tools, technology knowledge, and practical ideas that help people understand and use tech with more confidence.',
      'home.cta.read': 'Read latest notes',
      'home.cta.follow': 'Follow me',
      'home.cta.typeless': 'Typeless for you',
      'home.profile.title': 'I am 阿理哥 (Aligor).',
      'home.profile.body': 'I created aligor as my personal sharing space. I regularly analyze useful AI tools, tech trends, and simple ways to improve technology awareness.',
      'home.follow.label': 'Follow aligor',
      'home.follow.title': 'Follow my AI and tech updates',
      'home.follow.body': 'I will keep sharing content that helps you understand AI, choose better tools, and build stronger technology awareness.',
      'home.latest.title': 'Latest articles',
      'home.latest.label': 'Journal notes',
      'home.loading.label': 'Loading',
      'home.loading.body': 'Loading articles...',
      'home.about.title': 'About aligor',
      'home.about.label': 'Profile and links',
      'home.about.cardTitle': 'What I share',
      'home.about.cardBody': '<strong>aligor</strong> is where I share AI and technology knowledge in a practical, personal way. I focus on useful tools, tech awareness, and simple explanations that help people learn faster.',
      'home.tool.typeless': 'Typeless for You',
      'home.tool.typelessMeta': 'Download guide',
      'home.tool.articles': 'Latest articles',
      'home.tool.articlesMeta': 'Read notes',
      'home.tool.hotmail': 'Link AI Agent with Hotmail',
      'home.tool.hotmailMeta': 'OAuth2 guide',
      'card.read': 'Read',
      'empty.noPosts': 'No posts',
      'empty.noPostsBody': 'No articles yet. Drop a markdown file into <code>/articles/</code> and add it to <code>articles.json</code>.',
      'empty.error': 'Error',
      'empty.errorBody': 'Could not load articles. Check that <code>articles.json</code> is valid.',
      'article.back': 'Back to all articles',
      'article.loading': 'Loading article...',
      'footer.made': 'Made with',
      'typeless.eyebrow': 'Typeless for you',
      'typeless.title': 'Pick your <span class="gradient">download</span>',
      'typeless.intro': 'Smart voice dictation that turns speech into clear, polished writing on desktop and mobile.',
      'typeless.desktop.title': 'Desktop',
      'typeless.desktop.desc': 'Use Typeless on your computer for writing, replies, documents, and daily work.',
      'typeless.download.macos': 'Download for macOS',
      'typeless.download.windows': 'Download for Windows',
      'typeless.mobile.title': 'Mobile',
      'typeless.mobile.desc': 'Scan the QR code or use the store buttons to install Typeless on your phone.',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': 'Important tip',
      'typeless.tip.title': 'Use different emails on phone and computer',
      'typeless.tip.body': 'Typeless has a free weekly allowance. You can use up to <strong>8,000 words per week</strong>, and the allowance resets every Monday. If you install Typeless on both mobile and computer and want separate weekly word limits, do not use the same email on both devices.',
      'typeless.follow.label': 'Follow aligor',
      'typeless.follow.title': 'Follow me for more tech learning content',
      'typeless.follow.body': 'I regularly share analysis and practical content to help everyone improve their technology awareness and understand useful AI tools.',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': 'Working setup from my package',
      'hotmail.title': 'Hotmail / Outlook email automation with <span class="gradient">IMAP + OAuth2 + Python</span>',
      'hotmail.intro': 'This version follows the successful method from my package: register an Azure app, get a refresh token through Microsoft login, save it safely, then let Python refresh access tokens and connect to IMAP with XOAUTH2.',
      'hotmail.badge.safe': 'Refresh token method',
      'hotmail.badge.personal': 'Hotmail / Outlook.com',
      'hotmail.badge.imap': 'IMAP XOAUTH2',
      'hotmail.overview.title': 'The Working Flow',
      'hotmail.overview.body': 'The successful flow is: Refresh Token -> Microsoft token endpoint -> Access Token -> IMAP XOAUTH2 login -> read or organize mailbox. The script should save only the refresh token securely, refresh the access token automatically, and read headers with BODY.PEEK so emails are not marked as read.',
      'hotmail.steps.title': 'Working Steps',
      'hotmail.step1.title': 'Register the app in Azure Portal',
      'hotmail.step1.body': 'Open Azure Portal -> App registrations -> New registration. Name it something like Hotmail IMAP Client. For account type, choose personal Microsoft accounts only, or any Microsoft ID if you want broader support.',
      'hotmail.step2.title': 'Use the native client redirect URI',
      'hotmail.step2.body': 'Set Redirect URI type to Public client/native and use https://login.microsoftonline.com/common/oauth2/nativeclient. This matches the package method for manually collecting the authorization code.',
      'hotmail.step3.title': 'Copy the client ID and do not create a secret',
      'hotmail.step3.body': 'After registration, copy Application client ID. Because this is a public/native client flow, you do not need a client secret. Do not put secrets or real tokens inside the website or GitHub repo.',
      'hotmail.step4.title': 'Add IMAP delegated permission',
      'hotmail.step4.body': 'In API permissions, add delegated permission IMAP.AccessAsUser.All and make sure offline_access is included. These are needed so the script can read mail through IMAP and refresh access later.',
      'hotmail.step5.title': 'Get the authorization code in the browser',
      'hotmail.step5.body': 'Open the authorize URL with your client ID, nativeclient redirect URI, response_type=code, and the IMAP/offline_access scopes. After Microsoft login, copy the code value from the redirected URL.',
      'hotmail.step6.title': 'Use cURL to exchange code for refresh token',
      'hotmail.step6.body': 'POST the code to Microsoft token endpoint with grant_type=authorization_code. Save the refresh_token from the JSON response into macOS Keychain, then Python can refresh access tokens whenever it connects.',
      'hotmail.config.title': 'Values From the Working Package',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.redirect': 'Redirect URI',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': 'Main scopes to request',
      'hotmail.config.xoauth': 'XOAUTH2 format',
      'hotmail.safety.title': 'Very Important Rules',
      'hotmail.safety.one': 'Mask real emails, client IDs, access tokens, and refresh tokens before sharing screenshots or code.',
      'hotmail.safety.two': 'Store refresh tokens in macOS Keychain or a real secret manager, not inside scripts or GitHub.',
      'hotmail.safety.three': 'Use BODY.PEEK for reading headers so emails are not accidentally marked as read.',
      'hotmail.safety.four': 'Do not run permanent delete or automatic mailto unsubscribe without human approval.',
      'hotmail.token.title': 'Get Refresh Token',
      'hotmail.token.body': 'First open the authorize URL in a browser. After login, copy the code from the address bar. Then exchange it with cURL.',
      'hotmail.keychain.title': 'Save Token in macOS Keychain',
      'hotmail.keychain.body': 'The package stores the refresh token in Keychain, then Python reads it when refreshing the access token.',
      'hotmail.python.title': 'Python Connection Logic',
      'hotmail.python.body': 'Python reads the refresh token, calls Microsoft token endpoint, receives a fresh access token, then builds the XOAUTH2 string for IMAP login.',
      'hotmail.headers.title': 'Read Headers Only',
      'hotmail.headers.body': 'The working package reads only selected headers and uses BODY.PEEK. This keeps the mailbox private, faster, and avoids marking messages as read.',
      'hotmail.trouble.title': 'If It Fails, Check These First',
      'hotmail.trouble.auth': 'XOAUTH2 authentication failed: access token expired, wrong scope, or refresh token was not updated.',
      'hotmail.trouble.grant': 'AADSTS50158: password/ROPC flow is blocked by MFA or Microsoft security. Use the browser authorization code method.',
      'hotmail.trouble.consumer': 'AADSTS700016: app registration or client ID is wrong. Check the Azure Application client ID.',
      'hotmail.trouble.peek': 'Emails became read: the code used BODY[] instead of BODY.PEEK[]. Replace it globally.',
      'hotmail.references.title': 'Official References',
      'hotmail.references.body': 'This page is based on Microsoft Learn documentation for OAuth, IMAP/SMTP authentication, and Microsoft identity app registration.'
    },
    zh: {
      'nav.home': '首页',
      'nav.articles': '文章',
      'nav.typeless': 'Typeless',
      'nav.about': '关于',
      'nav.downloads': '下载',
      'nav.notes': '提示',
      'nav.hotmail': 'Hotmail 教程',
      'home.eyebrow': '个人分享博客',
      'home.title': '我是阿理哥。我分享 <span class="gradient">AI 与科技知识</span>。',
      'home.intro': '我目前主要分享 AI 工具、科技知识和实用想法，帮助大家更有信心地理解和使用科技。',
      'home.cta.read': '阅读最新笔记',
      'home.cta.follow': '追踪我',
      'home.cta.typeless': 'Typeless 下载',
      'home.profile.title': '我是阿理哥。',
      'home.profile.body': '我把 aligor 做成我的个人分享空间。我会定期分析实用 AI 工具、科技趋势，以及帮助大家提升科技认知的简单方法。',
      'home.follow.label': 'Follow aligor',
      'home.follow.title': '追踪我的 AI 与科技更新',
      'home.follow.body': '我会持续分享帮助你理解 AI、选择更好工具、提升科技认知的内容。',
      'home.latest.title': '最新文章',
      'home.latest.label': '个人笔记',
      'home.loading.label': '载入中',
      'home.loading.body': '正在载入文章...',
      'home.about.title': '关于 aligor',
      'home.about.label': '个人介绍与链接',
      'home.about.cardTitle': '我分享什么',
      'home.about.cardBody': '<strong>aligor</strong> 是我用个人化、实用方式分享 AI 与科技知识的地方。我会专注在实用工具、科技认知和简单易懂的解释，帮助大家更快学习。',
      'home.tool.typeless': 'Typeless 下载页',
      'home.tool.typelessMeta': '下载指南',
      'home.tool.articles': '最新文章',
      'home.tool.articlesMeta': '阅读笔记',
      'home.tool.hotmail': 'AI Agent 连接 Hotmail',
      'home.tool.hotmailMeta': 'OAuth2 教程',
      'card.read': '阅读',
      'empty.noPosts': '暂无文章',
      'empty.noPostsBody': '还没有文章。把 markdown 文件放进 <code>/articles/</code>，再加入 <code>articles.json</code>。',
      'empty.error': '错误',
      'empty.errorBody': '文章载入失败。请检查 <code>articles.json</code> 是否正确。',
      'article.back': '回到全部文章',
      'article.loading': '正在载入文章...',
      'footer.made': '制作',
      'typeless.eyebrow': 'Typeless 下载',
      'typeless.title': '选择你的 <span class="gradient">下载版本</span>',
      'typeless.intro': 'Typeless 是智能语音输入工具，可以把你说的话变成更清楚、更顺的文字，手机和电脑都可以使用。',
      'typeless.desktop.title': '电脑版本',
      'typeless.desktop.desc': '在电脑上使用 Typeless，适合写文章、回复信息、整理文件和日常工作。',
      'typeless.download.macos': '下载 macOS 版本',
      'typeless.download.windows': '下载 Windows 版本',
      'typeless.mobile.title': '手机版本',
      'typeless.mobile.desc': '扫描 QR code，或点击 App Store / Google Play 按钮安装 Typeless。',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': '重要小贴士',
      'typeless.tip.title': '手机和电脑请使用不同邮箱',
      'typeless.tip.body': 'Typeless 有免费的每周字数额度。你每个星期可以免费使用 <strong>8,000 字</strong>，额度会在每个星期一重置。如果你同时在手机和电脑安装 Typeless，想要分开计算每周字数额度，就不要在两个设备使用同一个邮箱。手机用一个邮箱，电脑用另一个邮箱。',
      'typeless.follow.label': 'Follow aligor',
      'typeless.follow.title': '追踪我，学习更多科技认知内容',
      'typeless.follow.body': '我会定期分析和分享帮助大家提升科技认知的内容，也会介绍实用 AI 工具和使用方法。',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': '照着我成功的包来做',
      'hotmail.title': 'Hotmail / Outlook 邮件自动化接入：<span class="gradient">IMAP + OAuth2 + Python</span>',
      'hotmail.intro': '这一版照着我给你的成功包来写：先在 Azure 注册 App，再通过 Microsoft 登录拿 Refresh Token，安全保存后，由 Python 自动刷新 Access Token，并用 IMAP XOAUTH2 连接邮箱。',
      'hotmail.badge.safe': 'Refresh Token 方法',
      'hotmail.badge.personal': 'Hotmail / Outlook.com',
      'hotmail.badge.imap': 'IMAP XOAUTH2',
      'hotmail.overview.title': '成功流程',
      'hotmail.overview.body': '成功流程是：Refresh Token -> Microsoft token endpoint -> Access Token -> IMAP XOAUTH2 登录 -> 读取或整理邮箱。脚本只需要安全保存 Refresh Token，Access Token 过期就自动刷新，并且读取邮件时用 BODY.PEEK，这样邮件不会被标记成已读。',
      'hotmail.steps.title': '照包步骤',
      'hotmail.step1.title': '在 Azure Portal 注册应用',
      'hotmail.step1.body': '打开 Azure Portal -> App registrations -> New registration。Name 可以写 Hotmail IMAP Client。Supported account types 可以选 Personal Microsoft accounts only；如果你要支持更多 Microsoft ID，也可以选 Any Microsoft ID。',
      'hotmail.step2.title': '使用 native client redirect URI',
      'hotmail.step2.body': 'Redirect URI 类型选 Public client/native，值填写 https://login.microsoftonline.com/common/oauth2/nativeclient。这就是包里用来手动拿 authorization code 的方法。',
      'hotmail.step3.title': '复制 client ID，不要创建 secret',
      'hotmail.step3.body': '注册完成后，复制 Application client ID。因为这个是 public/native client flow，不需要 client secret。不要把 secret 或真实 token 放进网页或 GitHub。',
      'hotmail.step4.title': '加入 IMAP delegated permission',
      'hotmail.step4.body': '到 API permissions 加 delegated permission：IMAP.AccessAsUser.All，并确保有 offline_access。这样脚本才能通过 IMAP 读取邮件，并且之后可以自动刷新 access token。',
      'hotmail.step5.title': '在浏览器获取 authorization code',
      'hotmail.step5.body': '打开 authorize URL，带上 client ID、nativeclient redirect URI、response_type=code，以及 IMAP/offline_access scopes。Microsoft 登录后，从跳转后的地址栏复制 code 值。',
      'hotmail.step6.title': '用 cURL 把 code 换成 refresh token',
      'hotmail.step6.body': '把 code POST 到 Microsoft token endpoint，grant_type=authorization_code。从返回的 JSON 复制 refresh_token，存进 macOS Keychain，之后 Python 每次连接时就能自动刷新 access token。',
      'hotmail.config.title': '成功包里的关键参数',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.redirect': 'Redirect URI',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': '要申请的主要 scopes',
      'hotmail.config.xoauth': 'XOAUTH2 格式',
      'hotmail.safety.title': '非常重要的规则',
      'hotmail.safety.one': '分享截图或代码前，要把真实 email、client ID、access token、refresh token 打码。',
      'hotmail.safety.two': 'Refresh Token 要存 macOS Keychain 或真正的 secret manager，不要写在脚本或 GitHub。',
      'hotmail.safety.three': '读取 Header 时一定用 BODY.PEEK，避免邮件被误标记为已读。',
      'hotmail.safety.four': '不要自动永久删除邮件，也不要未经人工确认就执行 mailto 退订。',
      'hotmail.token.title': '获取 Refresh Token',
      'hotmail.token.body': '先在浏览器打开 authorize URL。登录后，从地址栏复制 code，再用 cURL 换 refresh token。',
      'hotmail.keychain.title': '把 Token 存进 macOS Keychain',
      'hotmail.keychain.body': '成功包的做法是把 refresh token 存进 Keychain，Python 刷新 access token 时再读取。',
      'hotmail.python.title': 'Python 连接逻辑',
      'hotmail.python.body': 'Python 读取 refresh token，调用 Microsoft token endpoint，拿新的 access token，然后组装 XOAUTH2 字符串登录 IMAP。',
      'hotmail.headers.title': '只读 Header，不读正文',
      'hotmail.headers.body': '成功包只读取指定 Header，并且使用 BODY.PEEK。这样更快、更隐私，也不会把邮件标记为已读。',
      'hotmail.trouble.title': '失败时先检查这里',
      'hotmail.trouble.auth': 'XOAUTH2 authentication failed：通常是 access token 过期、scope 不对，或 refresh token 没有更新。',
      'hotmail.trouble.grant': 'AADSTS50158：password/ROPC flow 被 MFA 或 Microsoft 安全验证挡住，请用浏览器 authorization code 方法。',
      'hotmail.trouble.consumer': 'AADSTS700016：App Registration 不存在或 client ID 错误，请检查 Azure 的 Application client ID。',
      'hotmail.trouble.peek': '邮件被标记已读：代码用了 BODY[]，不是 BODY.PEEK[]。请全局替换。',
      'hotmail.references.title': '官方参考',
      'hotmail.references.body': '这个页面根据 Microsoft Learn 的 OAuth、IMAP/SMTP authentication 和 Microsoft identity app registration 文件整理。'
    },
    ms: {
      'nav.home': 'Laman utama',
      'nav.articles': 'Artikel',
      'nav.typeless': 'Typeless',
      'nav.about': 'Tentang',
      'nav.downloads': 'Muat turun',
      'nav.notes': 'Nota',
      'nav.hotmail': 'Panduan Hotmail',
      'home.eyebrow': 'Blog perkongsian peribadi',
      'home.title': 'Saya 阿理哥 (Aligor). Saya berkongsi <span class="gradient">ilmu AI dan teknologi</span>.',
      'home.intro': 'Saya kini fokus berkongsi alat AI, pengetahuan teknologi, dan idea praktikal supaya lebih ramai orang yakin memahami dan menggunakan teknologi.',
      'home.cta.read': 'Baca nota terkini',
      'home.cta.follow': 'Ikuti saya',
      'home.cta.typeless': 'Typeless untuk anda',
      'home.profile.title': 'Saya 阿理哥 (Aligor).',
      'home.profile.body': 'Saya menjadikan aligor sebagai ruang perkongsian peribadi. Saya kerap menganalisis alat AI, trend teknologi, dan cara mudah untuk meningkatkan kesedaran teknologi.',
      'home.follow.label': 'Ikuti aligor',
      'home.follow.title': 'Ikuti kemas kini AI dan teknologi saya',
      'home.follow.body': 'Saya akan terus berkongsi kandungan yang membantu anda memahami AI, memilih alat yang lebih baik, dan membina kesedaran teknologi yang lebih kuat.',
      'home.latest.title': 'Artikel terkini',
      'home.latest.label': 'Nota jurnal',
      'home.loading.label': 'Memuat',
      'home.loading.body': 'Sedang memuat artikel...',
      'home.about.title': 'Tentang aligor',
      'home.about.label': 'Profil dan pautan',
      'home.about.cardTitle': 'Apa yang saya kongsi',
      'home.about.cardBody': '<strong>aligor</strong> ialah tempat saya berkongsi ilmu AI dan teknologi secara praktikal dan peribadi. Saya fokus pada alat berguna, kesedaran teknologi, dan penerangan mudah supaya orang belajar dengan lebih cepat.',
      'home.tool.typeless': 'Typeless untuk Anda',
      'home.tool.typelessMeta': 'Panduan muat turun',
      'home.tool.articles': 'Artikel terkini',
      'home.tool.articlesMeta': 'Baca nota',
      'home.tool.hotmail': 'Hubungkan AI Agent dengan Hotmail',
      'home.tool.hotmailMeta': 'Panduan OAuth2',
      'card.read': 'Baca',
      'empty.noPosts': 'Tiada artikel',
      'empty.noPostsBody': 'Belum ada artikel. Letakkan fail markdown dalam <code>/articles/</code> dan tambahkannya ke <code>articles.json</code>.',
      'empty.error': 'Ralat',
      'empty.errorBody': 'Artikel gagal dimuat. Semak bahawa <code>articles.json</code> adalah sah.',
      'article.back': 'Kembali ke semua artikel',
      'article.loading': 'Sedang memuat artikel...',
      'footer.made': 'Dibuat dengan',
      'typeless.eyebrow': 'Typeless untuk anda',
      'typeless.title': 'Pilih <span class="gradient">muat turun</span> anda',
      'typeless.intro': 'Dikte suara pintar yang menukar percakapan kepada tulisan yang jelas dan kemas di desktop dan telefon.',
      'typeless.desktop.title': 'Desktop',
      'typeless.desktop.desc': 'Gunakan Typeless di komputer untuk menulis, membalas mesej, dokumen, dan kerja harian.',
      'typeless.download.macos': 'Muat turun untuk macOS',
      'typeless.download.windows': 'Muat turun untuk Windows',
      'typeless.mobile.title': 'Mudah alih',
      'typeless.mobile.desc': 'Imbas kod QR atau gunakan butang kedai aplikasi untuk memasang Typeless di telefon.',
      'typeless.appstore.kicker': 'Download on the',
      'typeless.appstore.title': 'App Store',
      'typeless.google.kicker': 'GET IT ON',
      'typeless.google.title': 'Google Play',
      'typeless.tip.label': 'Tip penting',
      'typeless.tip.title': 'Gunakan e-mel berbeza di telefon dan komputer',
      'typeless.tip.body': 'Typeless mempunyai kuota percuma mingguan. Anda boleh menggunakan sehingga <strong>8,000 perkataan seminggu</strong>, dan kuota akan reset setiap hari Isnin. Jika anda memasang Typeless pada telefon dan komputer serta mahukan had mingguan berasingan, jangan gunakan e-mel yang sama pada kedua-dua peranti.',
      'typeless.follow.label': 'Ikuti aligor',
      'typeless.follow.title': 'Ikuti saya untuk lebih banyak kandungan teknologi',
      'typeless.follow.body': 'Saya kerap berkongsi analisis dan kandungan praktikal untuk membantu semua orang meningkatkan kesedaran teknologi dan memahami alat AI yang berguna.',
      'typeless.follow.instagram': 'Instagram',
      'typeless.follow.facebook': 'Facebook',
      'typeless.follow.threads': 'Threads',
      'hotmail.eyebrow': 'Ikut pakej yang sudah berjaya',
      'hotmail.title': 'Automasi e-mel Hotmail / Outlook dengan <span class="gradient">IMAP + OAuth2 + Python</span>',
      'hotmail.intro': 'Versi ini ikut kaedah berjaya daripada pakej: daftar Azure app, dapatkan refresh token melalui Microsoft login, simpan dengan selamat, kemudian Python refresh access token dan sambung ke IMAP dengan XOAUTH2.',
      'hotmail.badge.safe': 'Kaedah refresh token',
      'hotmail.badge.personal': 'Hotmail / Outlook.com',
      'hotmail.badge.imap': 'IMAP XOAUTH2',
      'hotmail.overview.title': 'Aliran Yang Berjaya',
      'hotmail.overview.body': 'Aliran berjaya ialah: Refresh Token -> Microsoft token endpoint -> Access Token -> IMAP XOAUTH2 login -> baca atau susun mailbox. Skrip hanya simpan refresh token dengan selamat, refresh access token secara automatik, dan baca header dengan BODY.PEEK supaya e-mel tidak ditanda sebagai read.',
      'hotmail.steps.title': 'Langkah Pakej',
      'hotmail.step1.title': 'Daftar app dalam Azure Portal',
      'hotmail.step1.body': 'Buka Azure Portal -> App registrations -> New registration. Namakan seperti Hotmail IMAP Client. Untuk account type, pilih personal Microsoft accounts only, atau any Microsoft ID jika mahu sokongan lebih luas.',
      'hotmail.step2.title': 'Gunakan native client redirect URI',
      'hotmail.step2.body': 'Set Redirect URI type kepada Public client/native dan gunakan https://login.microsoftonline.com/common/oauth2/nativeclient. Ini sama seperti kaedah pakej untuk mengambil authorization code secara manual.',
      'hotmail.step3.title': 'Salin client ID dan jangan buat secret',
      'hotmail.step3.body': 'Selepas daftar, salin Application client ID. Kerana ini public/native client flow, client secret tidak diperlukan. Jangan letakkan secret atau token sebenar dalam website atau GitHub repo.',
      'hotmail.step4.title': 'Tambah IMAP delegated permission',
      'hotmail.step4.body': 'Dalam API permissions, tambah delegated permission IMAP.AccessAsUser.All dan pastikan offline_access ada. Ini diperlukan supaya skrip boleh baca e-mel melalui IMAP dan refresh akses kemudian.',
      'hotmail.step5.title': 'Dapatkan authorization code dalam browser',
      'hotmail.step5.body': 'Buka authorize URL dengan client ID, nativeclient redirect URI, response_type=code, dan scopes IMAP/offline_access. Selepas Microsoft login, salin nilai code daripada URL redirect.',
      'hotmail.step6.title': 'Guna cURL untuk tukar code kepada refresh token',
      'hotmail.step6.body': 'POST code ke Microsoft token endpoint dengan grant_type=authorization_code. Simpan refresh_token daripada JSON response ke macOS Keychain, kemudian Python boleh refresh access token bila menyambung.',
      'hotmail.config.title': 'Nilai Daripada Pakej Berjaya',
      'hotmail.config.auth': 'Authorization endpoint',
      'hotmail.config.token': 'Token endpoint',
      'hotmail.config.redirect': 'Redirect URI',
      'hotmail.config.imapHost': 'IMAP host',
      'hotmail.config.imapPort': 'IMAP port',
      'hotmail.config.scope': 'Scopes utama untuk diminta',
      'hotmail.config.xoauth': 'Format XOAUTH2',
      'hotmail.safety.title': 'Peraturan Sangat Penting',
      'hotmail.safety.one': 'Mask e-mel sebenar, client ID, access token, dan refresh token sebelum kongsi screenshot atau kod.',
      'hotmail.safety.two': 'Simpan refresh token dalam macOS Keychain atau secret manager sebenar, bukan dalam skrip atau GitHub.',
      'hotmail.safety.three': 'Gunakan BODY.PEEK untuk baca header supaya e-mel tidak tertanda sebagai read.',
      'hotmail.safety.four': 'Jangan buat permanent delete atau automatic mailto unsubscribe tanpa kelulusan manusia.',
      'hotmail.token.title': 'Dapatkan Refresh Token',
      'hotmail.token.body': 'Mula-mula buka authorize URL dalam browser. Selepas login, salin code daripada address bar. Kemudian tukar dengan cURL.',
      'hotmail.keychain.title': 'Simpan Token dalam macOS Keychain',
      'hotmail.keychain.body': 'Pakej ini menyimpan refresh token dalam Keychain, kemudian Python membacanya semasa refresh access token.',
      'hotmail.python.title': 'Logik Sambungan Python',
      'hotmail.python.body': 'Python membaca refresh token, memanggil Microsoft token endpoint, menerima access token baharu, kemudian membina string XOAUTH2 untuk login IMAP.',
      'hotmail.headers.title': 'Baca Header Sahaja',
      'hotmail.headers.body': 'Pakej berjaya hanya membaca header tertentu dan menggunakan BODY.PEEK. Ini lebih private, lebih laju, dan tidak menanda e-mel sebagai read.',
      'hotmail.trouble.title': 'Jika Gagal, Semak Ini Dulu',
      'hotmail.trouble.auth': 'XOAUTH2 authentication failed: access token tamat tempoh, scope salah, atau refresh token tidak dikemas kini.',
      'hotmail.trouble.grant': 'AADSTS50158: password/ROPC flow disekat oleh MFA atau keselamatan Microsoft. Guna kaedah browser authorization code.',
      'hotmail.trouble.consumer': 'AADSTS700016: app registration atau client ID salah. Semak Azure Application client ID.',
      'hotmail.trouble.peek': 'E-mel menjadi read: kod menggunakan BODY[] dan bukan BODY.PEEK[]. Ganti secara menyeluruh.',
      'hotmail.references.title': 'Rujukan Rasmi',
      'hotmail.references.body': 'Halaman ini berdasarkan dokumentasi Microsoft Learn untuk OAuth, pengesahan IMAP/SMTP, dan pendaftaran app Microsoft identity.'
    }
  };

  function getLanguage() {
    const saved = localStorage.getItem(STORAGE_KEY);
    return ['en', 'zh', 'ms'].includes(saved) ? saved : 'en';
  }

  function translateElement(el, lang) {
    const dictionary = translations[lang] || translations.en;
    const textKey = el.getAttribute('data-i18n');
    const htmlKey = el.getAttribute('data-i18n-html');

    if (htmlKey && dictionary[htmlKey]) {
      el.innerHTML = dictionary[htmlKey];
    } else if (textKey && dictionary[textKey]) {
      el.textContent = dictionary[textKey];
    }
  }

  function applyLanguage(lang) {
    const nextLang = ['en', 'zh', 'ms'].includes(lang) ? lang : 'en';
    document.documentElement.lang = nextLang === 'zh' ? 'zh-Hans' : nextLang;
    document.querySelectorAll('[data-i18n], [data-i18n-html]').forEach((el) => translateElement(el, nextLang));
    document.querySelectorAll('[data-lang-option]').forEach((button) => {
      const active = button.getAttribute('data-lang-option') === nextLang;
      button.classList.toggle('active', active);
      button.setAttribute('aria-pressed', active ? 'true' : 'false');
    });
  }

  window.aligorGetLang = getLanguage;
  window.aligorApplyLanguage = function () {
    applyLanguage(getLanguage());
  };

  document.addEventListener('click', (event) => {
    const button = event.target.closest('[data-lang-option]');
    if (!button) return;
    const selected = button.getAttribute('data-lang-option');
    const lang = ['en', 'zh', 'ms'].includes(selected) ? selected : 'en';
    localStorage.setItem(STORAGE_KEY, lang);
    applyLanguage(lang);
    window.dispatchEvent(new CustomEvent('aligor:languagechange', { detail: { lang } }));
  });

  document.addEventListener('DOMContentLoaded', () => applyLanguage(getLanguage()));
})();
